### ISSUE TITLE
Headers being !Sync prevents usage of `&Headers` in futures

### ISSUE THREAD

**Issue by Marwes** [dekellum/hyperx#17]
Due to the interior mutability in `Headers` it isn't possible to use shared references to it in futures without losing `Send`. Since `Send` futures can't be sent to a thread pool this means that `Headers` more or less can't be used with async/await.

**Comment by dekellum** [comment]
This appears to be due to the use of two `UnsafeCell` in the (internals) `Item`, used as `Headers` map value. These aren't `Sync`, "cannot be shared between threads safely":

* std::cell::UnsafeCell<std::option::Option<header::raw::Raw>>
* std::cell::UnsafeCell<header::internals::cell::PtrMap<std::boxed::Box<(dyn header::Header + std::marker::Send + std::marker::Sync + 'static)>>>

This is a significant amount of (unsafe) implementation. It's not currently clear to me if the usual alternative of replacing cells with atomics would be workable or safe.  Alternatively replacing with mutex's would add overhead for existing single-threaded use cases.  Ideas or PR's are welcome though.

Short of making `Headers` `Sync`; possible workarounds include:

* Move `Headers` (possibly after cloning) instead of passing by reference. 
* Convert (e.g. `Headers::into()`) to `http::HeaderMap` which is `Sync`.

**Comment by Marwes** [comment]
Yeah, I looked at what it would take and it didn't look easy. Ended up replacing hyperx with https://github.com/hyperium/headers as that does not cache the headers as hyperx does and therefore needs no interior mutability.

**Comment by dekellum** [comment]
Right, so that ends up looking similar to the second mentioned workaround.  The `Headers` struct is now only an optional part of hyperx, kept for compatibility. Typed headers can be parsed from and encoded to `HeaderMap` directly.

**Comment by dekellum** [comment]
With #18 merged and released, it should be more clear that the `Headers` struct is an optional (if `!Sync`) type retained for backward-compatibility.
